# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4f181aad0e9841e62f978750bb771123d9531940a3bf4e994b973456e6c199ced4a297a8afab591240a603772932bc5e255a51d64f850b8549efb502cffd7fc

test:
  secret_key_base: 38d8431544bdd4bacbb84f9acaec8897f17983c4168085f62c75b3b6039c320ef744d01f73957da2657ff28313af4c57c271a4df003c7a8974c16aeb3735db98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
